/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { NaosBoostPool__factory } from './NaosBoostPool__factory';
export { NaosStakingPools__factory } from './NaosStakingPools__factory';
