/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NaosBoostPool } from './NaosBoostPool';
export type { NaosStakingPools } from './NaosStakingPools';
export * as factories from './factories';
export { NaosBoostPool__factory } from './factories/NaosBoostPool__factory';
export { NaosStakingPools__factory } from './factories/NaosStakingPools__factory';
